import sqlite3
from pathlib import Path

DB_PATH = "medical_terms.db"


def create_db():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS terms (
            id INTEGER PRIMARY KEY,
            term TEXT UNIQUE NOT NULL,
            category TEXT,
            common_misrecognition TEXT
        )
    """)
    cur.execute("CREATE INDEX IF NOT EXISTS idx_term ON terms(term)")
    conn.commit()
    conn.close()


def seed_terms():
    terms = [

        # ── MEDICATIONS: Common oral ──────────────────────────────────────
        ("metformin", "medication", "met four min"),
        ("metformin ER", "medication", "met four min E R"),
        ("lisinopril", "medication", "lisin a pril"),
        ("atorvastatin", "medication", "a torva stat in"),
        ("rosuvastatin", "medication", "ro soo va stat in"),
        ("simvastatin", "medication", "sim va stat in"),
        ("amlodipine", "medication", "am lo di peen"),
        ("omeprazole", "medication", "oh mep ra zole"),
        ("pantoprazole", "medication", "pan toe pra zole"),
        ("esomeprazole", "medication", "ee so mep ra zole"),
        ("losartan", "medication", "lo sar tan"),
        ("valsartan", "medication", "val sar tan"),
        ("olmesartan", "medication", "ol me sar tan"),
        ("hydrochlorothiazide", "medication", "hydro chloro thigh a zide"),
        ("furosemide", "medication", "fur oh se mide"),
        ("spironolactone", "medication", "spy ron oh lak tone"),
        ("carvedilol", "medication", "car ve di lol"),
        ("metoprolol", "medication", "met oh pro lol"),
        ("metoprolol succinate", "medication", "met oh pro lol suck sin ate"),
        ("metoprolol tartrate", "medication", "met oh pro lol tar trate"),
        ("atenolol", "medication", "a ten oh lol"),
        ("bisoprolol", "medication", "by so pro lol"),
        ("diltiazem", "medication", "dil tie a zem"),
        ("verapamil", "medication", "ver ap a mil"),
        ("amiodarone", "medication", "am ee oh da rone"),
        ("digoxin", "medication", "di gox in"),
        ("warfarin", "medication", "war far in"),
        ("apixaban", "medication", "a pix a ban"),
        ("rivaroxaban", "medication", "ri var ox a ban"),
        ("dabigatran", "medication", "da big a tran"),
        ("clopidogrel", "medication", "clo pid oh grel"),
        ("aspirin", "medication", "ass prin"),
        ("ticagrelor", "medication", "tie kag re lor"),
        ("prasugrel", "medication", "pra soo grel"),
        ("heparin", "medication", "hep a rin"),
        ("enoxaparin", "medication", "ee nox a par in"),
        ("levothyroxine", "medication", "lee vo thy rox een"),
        ("liothyronine", "medication", "ly oh thy ro neen"),
        ("gabapentin", "medication", "gab a pen tin"),
        ("pregabalin", "medication", "pre gab a lin"),
        ("duloxetine", "medication", "doo lox e teen"),
        ("sertraline", "medication", "ser tra leen"),
        ("escitalopram", "medication", "es sigh tal oh pram"),
        ("fluoxetine", "medication", "floo ox e teen"),
        ("paroxetine", "medication", "par ox e teen"),
        ("venlafaxine", "medication", "ven la fax een"),
        ("bupropion", "medication", "byoo pro pee on"),
        ("mirtazapine", "medication", "mir taz a peen"),
        ("quetiapine", "medication", "kwee ty a peen"),
        ("olanzapine", "medication", "oh lan za peen"),
        ("risperidone", "medication", "ris per i done"),
        ("aripiprazole", "medication", "air i pip ra zole"),
        ("clonazepam", "medication", "klo naz e pam"),
        ("lorazepam", "medication", "lor az e pam"),
        ("alprazolam", "medication", "al praz oh lam"),
        ("diazepam", "medication", "die az e pam"),
        ("zolpidem", "medication", "zol pi dem"),
        ("hydroxyzine", "medication", "hy drox i zeen"),
        ("prednisone", "medication", "pred ni sone"),
        ("methylprednisolone", "medication", "meth il pred nis oh lone"),
        ("dexamethasone", "medication", "dex a meth a sone"),
        ("albuterol", "medication", "al byoo ter ol"),
        ("ipratropium", "medication", "ip ra tro pee um"),
        ("tiotropium", "medication", "tie oh tro pee um"),
        ("fluticasone", "medication", "floo tik a sone"),
        ("budesonide", "medication", "byoo des oh nide"),
        ("montelukast", "medication", "mon te loo kast"),
        ("cetirizine", "medication", "se teer i zeen"),
        ("loratadine", "medication", "lor at a deen"),
        ("fexofenadine", "medication", "fex oh fen a deen"),
        ("diphenhydramine", "medication", "dye fen hy dra meen"),
        ("ondansetron", "medication", "on dan se tron"),
        ("promethazine", "medication", "pro meth a zeen"),
        ("metoclopramide", "medication", "met oh klo pra mide"),
        ("loperamide", "medication", "lo per a mide"),
        ("polyethylene glycol", "medication", "poly ethylene glycol"),
        ("lactulose", "medication", "lak tyoo lose"),
        ("docusate", "medication", "dok yoo sate"),
        ("senna", "medication", "sen a"),
        ("ferrous sulfate", "medication", "ferrous sul fate"),
        ("cyanocobalamin", "medication", "sigh an oh koe bal a min"),
        ("folic acid", "medication", "fo lik acid"),
        ("cholecalciferol", "medication", "kole e kal sif er ol"),
        ("calcium carbonate", "medication", "kal see um kar bo nate"),
        ("alendronate", "medication", "a len dro nate"),
        ("risedronate", "medication", "rise ed ro nate"),
        ("denosumab", "medication", "den oh soo mab"),
        ("allopurinol", "medication", "al oh pyoor i nol"),
        ("febuxostat", "medication", "fe bux oh stat"),
        ("colchicine", "medication", "kol chi seen"),
        ("hydroxychloroquine", "medication", "hy drox ee klor oh kwin"),
        ("methotrexate", "medication", "meth oh trex ate"),
        ("sulfasalazine", "medication", "sul fa sal a zeen"),
        ("azathioprine", "medication", "ay za thy oh preen"),
        ("cyclosporine", "medication", "sigh klo spor een"),
        ("tacrolimus", "medication", "ta kroe li mus"),
        ("mycophenolate", "medication", "my ko fen oh late"),

        # ── MEDICATIONS: Antibiotics ──────────────────────────────────────
        ("amoxicillin", "medication", "a mox i sil in"),
        ("amoxicillin-clavulanate", "medication", "amoxicillin clav you lan ate"),
        ("azithromycin", "medication", "a zith ro my sin"),
        ("doxycycline", "medication", "dox ee sigh kleen"),
        ("ciprofloxacin", "medication", "sip ro flox a sin"),
        ("levofloxacin", "medication", "lee vo flox a sin"),
        ("moxifloxacin", "medication", "mox i flox a sin"),
        ("clindamycin", "medication", "klin da my sin"),
        ("trimethoprim-sulfamethoxazole", "medication", "TMP SMX"),
        ("nitrofurantoin", "medication", "ny tro fyoor an to in"),
        ("metronidazole", "medication", "me tro nid a zole"),
        ("fluconazole", "medication", "floo kon a zole"),
        ("vancomycin", "medication", "van ko my sin"),
        ("piperacillin-tazobactam", "medication", "pip er a sil in taz oh bak tam"),
        ("meropenem", "medication", "mer oh pen em"),
        ("ceftriaxone", "medication", "sef try ax one"),
        ("cefazolin", "medication", "sef az oh lin"),
        ("cephalexin", "medication", "sef a lex in"),

        # ── MEDICATIONS: Diabetes ─────────────────────────────────────────
        ("insulin glargine", "medication", "insulin glar jeen"),
        ("insulin detemir", "medication", "insulin det e meer"),
        ("insulin degludec", "medication", "insulin deg loo dek"),
        ("insulin lispro", "medication", "insulin lis pro"),
        ("insulin aspart", "medication", "insulin as part"),
        ("insulin glulisine", "medication", "insulin gloo li seen"),
        ("insulin regular", "medication", "regular insulin"),
        ("NPH insulin", "medication", "N P H insulin"),
        ("semaglutide", "medication", "sem a gloo tide"),
        ("liraglutide", "medication", "leer a gloo tide"),
        ("dulaglutide", "medication", "doo la gloo tide"),
        ("exenatide", "medication", "ex en a tide"),
        ("sitagliptin", "medication", "sit a glip tin"),
        ("saxagliptin", "medication", "sax a glip tin"),
        ("linagliptin", "medication", "lin a glip tin"),
        ("empagliflozin", "medication", "em pa gli flo zin"),
        ("dapagliflozin", "medication", "dap a gli flo zin"),
        ("canagliflozin", "medication", "kan a gli flo zin"),
        ("pioglitazone", "medication", "pie oh gli ta zone"),
        ("glipizide", "medication", "glip i zide"),
        ("glimepiride", "medication", "gly me pi ride"),
        ("glyburide", "medication", "gly byoor ide"),

        # ── DIAGNOSES: Cardiovascular ─────────────────────────────────────
        ("hypertension", "diagnosis", "high tension"),
        ("hypotension", "diagnosis", "low tension"),
        ("atrial fibrillation", "diagnosis", "A fib"),
        ("atrial flutter", "diagnosis", "a flutter"),
        ("ventricular fibrillation", "diagnosis", "V fib"),
        ("ventricular tachycardia", "diagnosis", "V tach"),
        ("supraventricular tachycardia", "diagnosis", "SVT"),
        ("heart block", "diagnosis", "heart block"),
        ("congestive heart failure", "diagnosis", "CHF"),
        ("heart failure with reduced ejection fraction", "diagnosis", "HFrEF"),
        ("heart failure with preserved ejection fraction", "diagnosis", "HFpEF"),
        ("myocardial infarction", "diagnosis", "MI"),
        ("ST elevation myocardial infarction", "diagnosis", "STEMI"),
        ("non-ST elevation myocardial infarction", "diagnosis", "NSTEMI"),
        ("unstable angina", "diagnosis", "unstable an ji na"),
        ("stable angina", "diagnosis", "stable an ji na"),
        ("coronary artery disease", "diagnosis", "CAD"),
        ("peripheral artery disease", "diagnosis", "PAD"),
        ("deep vein thrombosis", "diagnosis", "DVT"),
        ("pulmonary embolism", "diagnosis", "PE"),
        ("aortic stenosis", "diagnosis", "a or tic ste no sis"),
        ("mitral regurgitation", "diagnosis", "my tral re gur ji ta shun"),
        ("mitral stenosis", "diagnosis", "my tral ste no sis"),
        ("aortic regurgitation", "diagnosis", "a or tic re gur ji ta shun"),
        ("endocarditis", "diagnosis", "en do kar dy tis"),
        ("pericarditis", "diagnosis", "pair i kar dy tis"),
        ("cardiomyopathy", "diagnosis", "car dee oh my op a thee"),
        ("hypertrophic cardiomyopathy", "diagnosis", "HCM"),

        # ── DIAGNOSES: Pulmonary ──────────────────────────────────────────
        ("chronic obstructive pulmonary disease", "diagnosis", "COPD"),
        ("asthma", "diagnosis", "az ma"),
        ("pneumonia", "diagnosis", "new mo nya"),
        ("community-acquired pneumonia", "diagnosis", "CAP"),
        ("hospital-acquired pneumonia", "diagnosis", "HAP"),
        ("pleural effusion", "diagnosis", "plur al e fyoo zhun"),
        ("pneumothorax", "diagnosis", "new mo thor ax"),
        ("acute respiratory distress syndrome", "diagnosis", "ARDS"),
        ("obstructive sleep apnea", "diagnosis", "OSA"),
        ("pulmonary hypertension", "diagnosis", "pul mo ner ee hy per ten shun"),
        ("interstitial lung disease", "diagnosis", "ILD"),
        ("bronchiectasis", "diagnosis", "bron kee ek ta sis"),
        ("sarcoidosis", "diagnosis", "sar koy do sis"),

        # ── DIAGNOSES: Metabolic / Endocrine ──────────────────────────────
        ("diabetes mellitus type 1", "diagnosis", "T1DM"),
        ("diabetes mellitus type 2", "diagnosis", "T2DM"),
        ("diabetic ketoacidosis", "diagnosis", "DKA"),
        ("hyperosmolar hyperglycemic state", "diagnosis", "HHS"),
        ("hypothyroidism", "diagnosis", "hy po thy roid izm"),
        ("hyperthyroidism", "diagnosis", "hy per thy roid izm"),
        ("Hashimoto thyroiditis", "diagnosis", "hash ee mo to"),
        ("Graves disease", "diagnosis", "graves disease"),
        ("hyperlipidemia", "diagnosis", "hy per li pi dee me a"),
        ("hypertriglyceridemia", "diagnosis", "hy per try glis er i dee me a"),
        ("metabolic syndrome", "diagnosis", "met a bol ik sin drome"),
        ("obesity", "diagnosis", "oh bee si tee"),
        ("hyperkalemia", "diagnosis", "hy per ka lee me a"),
        ("hypokalemia", "diagnosis", "hy po ka lee me a"),
        ("hyponatremia", "diagnosis", "hy po na tree me a"),
        ("hypernatremia", "diagnosis", "hy per na tree me a"),
        ("hypercalcemia", "diagnosis", "hy per kal see me a"),
        ("hypocalcemia", "diagnosis", "hy po kal see me a"),
        ("hypomagnesemia", "diagnosis", "hy po mag ne zee me a"),
        ("hyperphosphatemia", "diagnosis", "hy per fos fa tee me a"),
        ("adrenal insufficiency", "diagnosis", "a dree nal in suf ish en see"),
        ("Cushing syndrome", "diagnosis", "koosh ing"),
        ("hyperaldosteronism", "diagnosis", "hy per al dos ter on izm"),

        # ── DIAGNOSES: Renal ──────────────────────────────────────────────
        ("acute kidney injury", "diagnosis", "AKI"),
        ("chronic kidney disease", "diagnosis", "CKD"),
        ("end-stage renal disease", "diagnosis", "ESRD"),
        ("nephrotic syndrome", "diagnosis", "nef rot ik sin drome"),
        ("nephritic syndrome", "diagnosis", "nef rit ik sin drome"),
        ("glomerulonephritis", "diagnosis", "glom er yoo lo nef ry tis"),
        ("pyelonephritis", "diagnosis", "pie eh lo nef ry tis"),
        ("urinary tract infection", "diagnosis", "UTI"),
        ("nephrolithiasis", "diagnosis", "nef ro li thy a sis"),
        ("renal artery stenosis", "diagnosis", "RAS"),
        ("polycystic kidney disease", "diagnosis", "PKD"),
        ("hydronephrosis", "diagnosis", "hy dro nef ro sis"),

        # ── DIAGNOSES: Neurological ───────────────────────────────────────
        ("cerebrovascular accident", "diagnosis", "CVA"),
        ("transient ischemic attack", "diagnosis", "TIA"),
        ("ischemic stroke", "diagnosis", "iske mik stroke"),
        ("hemorrhagic stroke", "diagnosis", "hem or aj ik stroke"),
        ("subarachnoid hemorrhage", "diagnosis", "sub a rak noid hem or ij"),
        ("subdural hematoma", "diagnosis", "sub dur al hem a to ma"),
        ("epidural hematoma", "diagnosis", "ep i dur al hem a to ma"),
        ("seizure disorder", "diagnosis", "see zhur"),
        ("epilepsy", "diagnosis", "ep i lep see"),
        ("status epilepticus", "diagnosis", "stay tus ep i lep ti kus"),
        ("Parkinson disease", "diagnosis", "park in sun"),
        ("Alzheimer disease", "diagnosis", "alts hy mer"),
        ("dementia", "diagnosis", "de men sha"),
        ("multiple sclerosis", "diagnosis", "MS"),
        ("myasthenia gravis", "diagnosis", "my as thee nee a gra vis"),
        ("Guillain-Barre syndrome", "diagnosis", "ghee yan bar ray"),
        ("meningitis", "diagnosis", "men in jy tis"),
        ("encephalitis", "diagnosis", "en sef a ly tis"),
        ("migraine", "diagnosis", "my grain"),
        ("neuropathy", "diagnosis", "ner op a thee"),
        ("peripheral neuropathy", "diagnosis", "per if er al ner op a thee"),

        # ── DIAGNOSES: GI ─────────────────────────────────────────────────
        ("gastroesophageal reflux disease", "diagnosis", "GERD"),
        ("peptic ulcer disease", "diagnosis", "PUD"),
        ("Helicobacter pylori", "diagnosis", "H pylori"),
        ("inflammatory bowel disease", "diagnosis", "IBD"),
        ("Crohn disease", "diagnosis", "krone"),
        ("ulcerative colitis", "diagnosis", "ul ser a tiv ko ly tis"),
        ("irritable bowel syndrome", "diagnosis", "IBS"),
        ("diverticulitis", "diagnosis", "dy ver tik yoo ly tis"),
        ("diverticulosis", "diagnosis", "dy ver tik yoo lo sis"),
        ("appendicitis", "diagnosis", "a pen di sy tis"),
        ("pancreatitis", "diagnosis", "pan kree a ty tis"),
        ("cholecystitis", "diagnosis", "kole ee sis ty tis"),
        ("cholelithiasis", "diagnosis", "kole ee li thy a sis"),
        ("hepatitis", "diagnosis", "hep a ty tis"),
        ("cirrhosis", "diagnosis", "sir oh sis"),
        ("hepatic encephalopathy", "diagnosis", "hep at ik en sef a lop a thee"),
        ("ascites", "diagnosis", "a sy teez"),
        ("esophageal varices", "diagnosis", "e sof a jee al var i seez"),
        ("gastrointestinal bleed", "diagnosis", "GI bleed"),
        ("celiac disease", "diagnosis", "see lee ak"),

        # ── DIAGNOSES: Musculoskeletal ────────────────────────────────────
        ("osteoarthritis", "diagnosis", "os tee oh ar thry tis"),
        ("rheumatoid arthritis", "diagnosis", "roo ma toyd ar thry tis"),
        ("gout", "diagnosis", "gowt"),
        ("psoriatic arthritis", "diagnosis", "sor ee at ik"),
        ("ankylosing spondylitis", "diagnosis", "ank i lo sing spon di ly tis"),
        ("systemic lupus erythematosus", "diagnosis", "SLE"),
        ("fibromyalgia", "diagnosis", "fy bro my al jee a"),
        ("osteoporosis", "diagnosis", "os tee oh po ro sis"),
        ("osteomyelitis", "diagnosis", "os tee oh my e ly tis"),
        ("septic arthritis", "diagnosis", "sep tik ar thry tis"),
        ("rhabdomyolysis", "diagnosis", "rab do my ol i sis"),

        # ── DIAGNOSES: Hematology / Oncology ─────────────────────────────
        ("anemia", "diagnosis", "a nee me a"),
        ("iron deficiency anemia", "diagnosis", "IDA"),
        ("pernicious anemia", "diagnosis", "per nish us a nee me a"),
        ("sickle cell disease", "diagnosis", "SCD"),
        ("thalassemia", "diagnosis", "thal a see me a"),
        ("thrombocytopenia", "diagnosis", "throm bo sy to pee nee a"),
        ("leukopenia", "diagnosis", "loo ko pee nee a"),
        ("pancytopenia", "diagnosis", "pan sy to pee nee a"),
        ("polycythemia vera", "diagnosis", "pol ee sy thee me a vera"),
        ("leukemia", "diagnosis", "loo kee me a"),
        ("lymphoma", "diagnosis", "lim fo ma"),
        ("multiple myeloma", "diagnosis", "my e lo ma"),
        ("disseminated intravascular coagulation", "diagnosis", "DIC"),
        ("hypercoagulable state", "diagnosis", "hy per ko ag yoo la bul"),

        # ── DIAGNOSES: Infectious ─────────────────────────────────────────
        ("sepsis", "diagnosis", "sep sis"),
        ("septic shock", "diagnosis", "sep tik shock"),
        ("bacteremia", "diagnosis", "bak teer ee me a"),
        ("cellulitis", "diagnosis", "sel yoo ly tis"),
        ("necrotizing fasciitis", "diagnosis", "nek ro ty zing fash ee eye tis"),
        ("influenza", "diagnosis", "in floo en za"),
        ("COVID-19", "diagnosis", "covid nineteen"),
        ("SARS-CoV-2", "diagnosis", "sars cov two"),
        ("HIV", "diagnosis", "H I V"),
        ("AIDS", "diagnosis", "aydz"),
        ("tuberculosis", "diagnosis", "TB"),
        ("Clostridioides difficile", "diagnosis", "C diff"),
        ("MRSA", "diagnosis", "M R S A"),
        ("VRE", "diagnosis", "V R E"),

        # ── PROCEDURES ───────────────────────────────────────────────────
        ("electrocardiogram", "procedure", "EKG"),
        ("echocardiogram", "procedure", "echo"),
        ("cardiac catheterization", "procedure", "cath"),
        ("percutaneous coronary intervention", "procedure", "PCI"),
        ("coronary artery bypass graft", "procedure", "CABG"),
        ("implantable cardioverter defibrillator", "procedure", "ICD"),
        ("cardiac resynchronization therapy", "procedure", "CRT"),
        ("computed tomography", "procedure", "CT scan"),
        ("magnetic resonance imaging", "procedure", "MRI"),
        ("positron emission tomography", "procedure", "PET scan"),
        ("upper endoscopy", "procedure", "EGD"),
        ("colonoscopy", "procedure", "ko lon os ko pee"),
        ("bronchoscopy", "procedure", "bron kos ko pee"),
        ("thoracentesis", "procedure", "thor a sen tee sis"),
        ("paracentesis", "procedure", "pair a sen tee sis"),
        ("lumbar puncture", "procedure", "LP"),
        ("bone marrow biopsy", "procedure", "bone marrow biopsy"),
        ("hemodialysis", "procedure", "hee mo dy al i sis"),
        ("peritoneal dialysis", "procedure", "per i to nee al dy al i sis"),
        ("continuous renal replacement therapy", "procedure", "CRRT"),
        ("intubation", "procedure", "in too bay shun"),
        ("mechanical ventilation", "procedure", "mech vent"),
        ("tracheostomy", "procedure", "tray kee os to mee"),
        ("central venous catheter", "procedure", "CVC"),
        ("peripherally inserted central catheter", "procedure", "PICC line"),
        ("arterial line", "procedure", "a line"),
        ("chest tube", "procedure", "chest tube"),
        ("cardioversion", "procedure", "kar dee oh ver zhun"),
        ("defibrillation", "procedure", "dee fib ri lay shun"),

        # ── CLINICAL FINDINGS ─────────────────────────────────────────────
        ("tachycardia", "finding", "take a cardia"),
        ("bradycardia", "finding", "brady cardia"),
        ("tachypnea", "finding", "tak ip nee a"),
        ("bradypnea", "finding", "brad ip nee a"),
        ("dyspnea", "finding", "disp nee a"),
        ("orthopnea", "finding", "or thop nee a"),
        ("diaphoresis", "finding", "dy a fo ree sis"),
        ("cyanosis", "finding", "sy a no sis"),
        ("jaundice", "finding", "jawn dis"),
        ("edema", "finding", "e dee ma"),
        ("anasarca", "finding", "an a sar ka"),
        ("rales", "finding", "rails"),
        ("rhonchi", "finding", "ron ky"),
        ("wheezing", "finding", "weezing"),
        ("stridor", "finding", "stry dor"),
        ("crepitus", "finding", "krep i tus"),
        ("hepatomegaly", "finding", "hep a to meg a lee"),
        ("splenomegaly", "finding", "splee no meg a lee"),
        ("lymphadenopathy", "finding", "lim fad e nop a thee"),
        ("jugular venous distension", "finding", "JVD"),
        ("papilledema", "finding", "pap il e dee ma"),
        ("nystagmus", "finding", "ni stag mus"),
        ("ataxia", "finding", "a tak see a"),
        ("dysarthria", "finding", "dis ar three a"),
        ("aphasia", "finding", "a fay zhuh"),
        ("hemiplegia", "finding", "hem ee plee jee a"),
        ("hemiparesis", "finding", "hem ee pa ree sis"),
        ("asterixis", "finding", "as ter ix is"),
        ("Babinski sign", "finding", "ba bin skee"),

        # ── LAB VALUES / TESTS ────────────────────────────────────────────
        ("hemoglobin A1c", "lab", "H b A one c"),
        ("brain natriuretic peptide", "lab", "BNP"),
        ("N-terminal pro-BNP", "lab", "NT pro BNP"),
        ("troponin", "lab", "tro po nin"),
        ("creatinine", "lab", "kree at i neen"),
        ("blood urea nitrogen", "lab", "BUN"),
        ("glomerular filtration rate", "lab", "GFR"),
        ("international normalized ratio", "lab", "INR"),
        ("partial thromboplastin time", "lab", "PTT"),
        ("prothrombin time", "lab", "PT"),
        ("complete blood count", "lab", "CBC"),
        ("comprehensive metabolic panel", "lab", "CMP"),
        ("basic metabolic panel", "lab", "BMP"),
        ("lipid panel", "lab", "lipid panel"),
        ("thyroid stimulating hormone", "lab", "TSH"),
        ("erythrocyte sedimentation rate", "lab", "ESR"),
        ("C-reactive protein", "lab", "CRP"),
        ("procalcitonin", "lab", "pro kal si to nin"),
        ("lactate", "lab", "lak tate"),
        ("albumin", "lab", "al byoo min"),
        ("alkaline phosphatase", "lab", "alk phos"),
        ("alanine aminotransferase", "lab", "ALT"),
        ("aspartate aminotransferase", "lab", "AST"),
        ("total bilirubin", "lab", "total bili"),
        ("direct bilirubin", "lab", "direct bili"),
        ("urinalysis", "lab", "U A"),
        ("urine culture", "lab", "urine cx"),
        ("blood culture", "lab", "blood cx"),

    ]

    conn = sqlite3.connect(DB_PATH)
    conn.executemany(
        "INSERT OR IGNORE INTO terms (term, category, common_misrecognition) VALUES (?, ?, ?)",
        terms,
    )
    conn.commit()
    inserted = conn.execute("SELECT COUNT(*) FROM terms").fetchone()[0]
    conn.close()
    return inserted


if __name__ == "__main__":
    create_db()
    count = seed_terms()
    print(f"\n✅ Medical DB ready: {Path(DB_PATH).absolute()}")
    print(f"   Total terms in database: {count}")
    print("\nCategories seeded:")
    print("  • Medications (oral, antibiotics, diabetes, cardiac, psych, etc.)")
    print("  • Diagnoses (CV, pulmonary, metabolic, renal, neuro, GI, heme, ID)")
    print("  • Procedures (cardiac, imaging, GI, critical care, vascular)")
    print("  • Clinical Findings")
    print("  • Lab Values / Tests")
